-- Add comment to SampleEvent

Update hsdb.SampleEvent
Set Comments = 'Station visited, but no oysters collected.'
where SampleEventID = 'ABCOLL_20220201_1_0102_1' OR
SampleEventID = 'ABCOLL_20221005_1_0102_1'

-- Fix Location
Update hsdb.SampleEvent
Set LongitudeDec = -85.08935
where SampleEventID = 'ABCOLL_20221205_1_0158_1'

-- Add comments for WQ out of range

UPDATE hsdb.SampleEventWQ
SET Comments =
	CASE
WHEN SampleEventWQID = 'ABCOLL_20220104_1_0007_1_01' THEN 'Salinity outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220201_1_0007_1_01' THEN 'Salinity outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220404_1_0007_1_01' THEN 'Salinity outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20210802_1_0091_1_01' THEN 'pH not recorded; DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211101_1_0007_1_01' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211101_1_0007_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211101_1_0011_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211101_1_0091_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211202_1_0158_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211202_1_0007_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20211202_1_0011_1_01' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220104_1_0096_1_01' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220104_1_0096_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220201_1_0158_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220201_1_0091_1_01' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220201_1_0102_1_02' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220705_1_0102_1_01' THEN 'DO outside expected range'
WHEN SampleEventWQID = 'ABCOLL_20220502_1_0007_1_02' THEN 'Turbidity outside expected range'
ELSE Comments
END;

-- Fix CI error

Update hsdb.ConditionIndex
Set ShellWetWeight = 192.82
where OysterID = 'ABWC2211-11'

-- Add comments to CI

UPDATE hsdb.ConditionIndex
SET Comments =
	CASE
WHEN OysterID = 'ABWC2107-13' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2107-08' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2107-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2107-16' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2107-21' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2108-10' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2108-12' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2108-18' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2108-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2108-19' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2108-24' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2109-18' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2109-20' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2109-06' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2109-21' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2110-07' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2110-10' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2111-01' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2111-19' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2112-02' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2112-11' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2201-11' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2201-03' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2201-03' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2202-13' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2202-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2202-16' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2202-20' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2202-21' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2202-22' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2202-08' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2203-09' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2204-06' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2204-16' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2206-08' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2207-14' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2207-25' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2208-19' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2208-23' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCC2209-01' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABEC2210-04' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWC2204-09' THEN 'ShellLength and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2207-02' THEN 'ShellLength and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2201-07' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWC2201-08' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWC2203-17' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABEC2203-16' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABEC2203-17' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWC2204-04' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWC2204-18' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABEC2109-01' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABEC2109-07' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2204-16' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2205-13' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2206-04' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2206-20' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-21' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2210-04' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2210-08' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2210-22' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2212-10' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWC2112-03' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2203-04' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2204-14' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2204-22' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2204-25' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2205-01' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2206-22' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2207-01' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2207-09' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-04' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-07' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-08' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-19' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-20' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2208-23' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2209-07' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2212-05' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWC2212-06' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABCC2109-13' THEN 'TotalWeight sums outside expected range'
WHEN OysterID = 'ABEC2107-24' THEN 'TotalWeight sums and ShellWetWeight outside expected range'
WHEN OysterID = 'ABWC2210-21' THEN 'TissueWetWeight outside expected range'
WHEN OysterID = 'ABCC2205-15' THEN 'ShellWetWeight outside expected range'
WHEN OysterID = 'ABCC2209-24' THEN 'ShellDryWeight outside expected range'
ELSE Comments
END;


-- Add comments to Dermo

UPDATE hsdb.Dermo
SET Comments =
	CASE
WHEN OysterID = 'ABCD2107-02' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2107-07' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2107-08' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2107-04' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2107-12' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2107-17' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2107-20' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2107-22' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2107-24' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2108-17' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2108-13' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2109-20' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2109-21' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2110-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2110-25' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2112-14' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2112-18' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2112-25' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2202-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2202-17' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2203-11' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2203-05' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2203-06' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2203-10' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2204-19' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2204-25' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2205-08' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2206-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABCD2206-15' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABED2206-04' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2208-25' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2210-14' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2212-16' THEN 'ShellLength outside expected range'
WHEN OysterID = 'ABWD2212-06' THEN 'ShellLength and ShellWidth outside expected range'
WHEN OysterID = 'ABED2107-05' THEN 'ShellLength and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2108-01' THEN 'ShellLength and TotalWeight outside expected range'
WHEN OysterID = 'ABCD2108-02' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWD2112-22' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABCD2206-20' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABCD2207-18' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABCD2207-22' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABCD2208-07' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWD2209-23' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABWD2211-04' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABED2211-18' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABED2211-22' THEN 'ShellWidth outside expected range'
WHEN OysterID = 'ABCD2108-01' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2204-08' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2206-02' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2206-24' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2207-10' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2209-06' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2210-08' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2212-08' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2212-09' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABWD2212-11' THEN 'ShellWidth and TotalWeight outside expected range'
WHEN OysterID = 'ABCD2107-05' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABED2202-02' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2203-03' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2203-09' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2204-03' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2204-16' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2205-03' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2206-21' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2206-23' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2206-25' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2207-01' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2207-25' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2208-10' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2208-12' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2209-10' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2209-13' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2210-01' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2210-05' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2210-09' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2211-06' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2211-12' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2212-02' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABWD2212-13' THEN 'TotalWeight outside expected range'
WHEN OysterID = 'ABCD2205-16' THEN 'ShellWetWeight outside expected range'
ELSE Comments
END;