
INSERT INTO [hsdb].[SampleEventWQ]
    ([SampleEventWQID]
      ,[SampleEventID]
      ,[Temperature]
      ,[Salinity]
      ,[DissolvedOxygen]
      ,[pH]
      ,[Depth]
      ,[SampleDepth]
      ,[Secchi]
      ,[TurbidityYSI]
      ,[TurbidityHach]
      ,[DataStatus]
      ,[DateEntered]
      ,[EnteredBy]
      ,[DateProofed]
      ,[ProofedBy]
      ,[DateCompleted]
      ,[CompletedBy]
      ,[Comments]
      ,[AdminNotes]
      ,[CollectionTime]
      ,[PercentDissolvedOxygen]
      ,[YSICalibration]
      ,[YSINotes])
  VALUES
      ('TBRCRT_20080318_1_0278_1_01'
      ,'TBRCRT_20080318_1_0278_1'
      ,'20.3'
      ,'31.5'
      ,'6.08'
      ,''
      ,'0.5'
      ,'0.5'
      ,'0.5'
      ,''
      ,''
      ,'Proofed'
      ,'2024-12-17'
      ,'Erica Williams'
      ,'2024-12-17'
      ,'Erica Williams'
      ,''
      ,''
      ,''
      ,''
      ,'0830'
      ,''
      ,''
      ,'')
 GO


INSERT INTO [hsdb].[SampleEventWQ]
    ([SampleEventWQID]
      ,[SampleEventID]
      ,[Temperature]
      ,[Salinity]
      ,[DissolvedOxygen]
      ,[pH]
      ,[Depth]
      ,[SampleDepth]
      ,[Secchi]
      ,[TurbidityYSI]
      ,[TurbidityHach]
      ,[DataStatus]
      ,[DateEntered]
      ,[EnteredBy]
      ,[DateProofed]
      ,[ProofedBy]
      ,[DateCompleted]
      ,[CompletedBy]
      ,[Comments]
      ,[AdminNotes]
      ,[CollectionTime]
      ,[PercentDissolvedOxygen]
      ,[YSICalibration]
      ,[YSINotes])
  VALUES
      ('TBRCRT_20080318_1_0279_1_01'
      ,'TBRCRT_20080318_1_0279_1'
      ,'20.7'
      ,'33.1'
      ,'5.75'
      ,''
      ,'0.75'
      ,'0.75'
      ,'0.75'
      ,''
      ,''
      ,'Proofed'
      ,'2024-12-17'
      ,'Erica Williams'
      ,'2024-12-17'
      ,'Erica Williams'
      ,''
      ,''
      ,''
      ,''
      ,'0840'
      ,''
      ,''
      ,'')
 GO


INSERT INTO [hsdb].[SampleEventWQ]
    ([SampleEventWQID]
      ,[SampleEventID]
      ,[Temperature]
      ,[Salinity]
      ,[DissolvedOxygen]
      ,[pH]
      ,[Depth]
      ,[SampleDepth]
      ,[Secchi]
      ,[TurbidityYSI]
      ,[TurbidityHach]
      ,[DataStatus]
      ,[DateEntered]
      ,[EnteredBy]
      ,[DateProofed]
      ,[ProofedBy]
      ,[DateCompleted]
      ,[CompletedBy]
      ,[Comments]
      ,[AdminNotes]
      ,[CollectionTime]
      ,[PercentDissolvedOxygen]
      ,[YSICalibration]
      ,[YSINotes])
  VALUES
      ('TBRCRT_20080318_1_0281_1_01'
      ,'TBRCRT_20080318_1_0281_1'
      ,'20.3'
      ,'33.7'
      ,'5.21'
      ,''
      ,'1'
      ,'1'
      ,'1'
      ,''
      ,''
      ,'Proofed'
      ,'2024-12-17'
      ,'Erica Williams'
      ,'2024-12-17'
      ,'Erica Williams'
      ,''
      ,''
      ,''
      ,''
      ,'0900'
      ,''
      ,''
      ,'')
 GO


INSERT INTO [hsdb].[SampleEventWQ]
    ([SampleEventWQID]
      ,[SampleEventID]
      ,[Temperature]
      ,[Salinity]
      ,[DissolvedOxygen]
      ,[pH]
      ,[Depth]
      ,[SampleDepth]
      ,[Secchi]
      ,[TurbidityYSI]
      ,[TurbidityHach]
      ,[DataStatus]
      ,[DateEntered]
      ,[EnteredBy]
      ,[DateProofed]
      ,[ProofedBy]
      ,[DateCompleted]
      ,[CompletedBy]
      ,[Comments]
      ,[AdminNotes]
      ,[CollectionTime]
      ,[PercentDissolvedOxygen]
      ,[YSICalibration]
      ,[YSINotes])
  VALUES
      ('TBRCRT_20080318_1_0278_1_01'
      ,'TBRCRT_20080318_1_0278_1'
      ,'20.3'
      ,'31.5'
      ,'6.08'
      ,''
      ,'0.5'
      ,'0.5'
      ,'0.5'
      ,''
      ,''
      ,'Proofed'
      ,'2024-12-17'
      ,'Erica Williams'
      ,'2024-12-17'
      ,'Erica Williams'
      ,''
      ,''
      ,''
      ,''
      ,'0830'
      ,''
      ,''
      ,'')
 GO


INSERT INTO [hsdb].[SampleEventWQ]
    ([SampleEventWQID]
      ,[SampleEventID]
      ,[Temperature]
      ,[Salinity]
      ,[DissolvedOxygen]
      ,[pH]
      ,[Depth]
      ,[SampleDepth]
      ,[Secchi]
      ,[TurbidityYSI]
      ,[TurbidityHach]
      ,[DataStatus]
      ,[DateEntered]
      ,[EnteredBy]
      ,[DateProofed]
      ,[ProofedBy]
      ,[DateCompleted]
      ,[CompletedBy]
      ,[Comments]
      ,[AdminNotes]
      ,[CollectionTime]
      ,[PercentDissolvedOxygen]
      ,[YSICalibration]
      ,[YSINotes])
  VALUES
      ('TBRCRT_20080318_1_0279_1_01'
      ,'TBRCRT_20080318_1_0279_1'
      ,'20.7'
      ,'33.1'
      ,'5.75'
      ,''
      ,'0.75'
      ,'0.75'
      ,'0.75'
      ,''
      ,''
      ,'Proofed'
      ,'2024-12-17'
      ,'Erica Williams'
      ,'2024-12-17'
      ,'Erica Williams'
      ,''
      ,''
      ,''
      ,''
      ,'0840'
      ,''
      ,''
      ,'')
 GO


INSERT INTO [hsdb].[SampleEventWQ]
    ([SampleEventWQID]
      ,[SampleEventID]
      ,[Temperature]
      ,[Salinity]
      ,[DissolvedOxygen]
      ,[pH]
      ,[Depth]
      ,[SampleDepth]
      ,[Secchi]
      ,[TurbidityYSI]
      ,[TurbidityHach]
      ,[DataStatus]
      ,[DateEntered]
      ,[EnteredBy]
      ,[DateProofed]
      ,[ProofedBy]
      ,[DateCompleted]
      ,[CompletedBy]
      ,[Comments]
      ,[AdminNotes]
      ,[CollectionTime]
      ,[PercentDissolvedOxygen]
      ,[YSICalibration]
      ,[YSINotes])
  VALUES
      ('TBRCRT_20080318_1_0281_1_01'
      ,'TBRCRT_20080318_1_0281_1'
      ,'20.3'
      ,'33.7'
      ,'5.21'
      ,''
      ,'1'
      ,'1'
      ,'1'
      ,''
      ,''
      ,'Proofed'
      ,'2024-12-17'
      ,'Erica Williams'
      ,'2024-12-17'
      ,'Erica Williams'
      ,''
      ,''
      ,''
      ,''
      ,'0900'
      ,''
      ,''
      ,'')
 GO
